### ISSUE TITLE
Linux error while loading shared libraries

### ISSUE THREAD

**Issue by lucasdc6** [CMATHL/cml#14]
Al compilar un programa con la librería, y ejecutarlo, tira el siguiente error:

`Linux error while loading shared libraries: cannot open shared object file: No such file or directory`

Buscando, encontré el siguiente [post en stackoverflow](https://stackoverflow.com/questions/480764/linux-error-while-loading-shared-libraries-cannot-open-shared-object-file-no-s) que espero te ayude.

**Comment by ulises-jeremias** [comment]
Hola Lucas, antes que nada, gracias por la issue :+1:. Estuve evaluando los casos en los que salta el error y claramente no tuve en cuenta algunos aspectos al momento de definir la instalación. Lo que pasa es lo siguiente, gcc busca, durante el proceso de enlazamiento, la librería en determinados directorios que pueden no ser los que cmake determine como apropiados para la instalación. Por defecto en la mayoría de los casos, la librería se instalará en /usr/local. Luego, si bien encuentra la librería en ese directorio puede suceder el caso en el que, como describe el error, no sea accesible, y esto no es nada menos que un problema en como esta definido `ld`, siendo este el comando el cual utiliza gcc, u otros compiladores como clang, para resolver los enlazamientos. Momentáneamente, este problema puede resolverse en tiempo de compilación con gcc, agregando algunos flags del siguiente estilo,

```shell
$ gcc -lcml main.c -o main -L<path> -Wl,-R<path>
```
siendo <path> la ruta a la librearía, como por ejemplo, /usr/local/lib, /usr/local/lib64 ó /usr/lib64, dependiendo de la arquitectura y del OS en el cual se esté compilando. 

Esta solución rápida supone un problema, y es que se deben definir las rutas en cada compilación. Ahora, sabiendo que el problema es de `ld` y no de gcc, podemos resolverlo por otras vías. Se podría por ejemplo, 
```shell
$ export LD_LIBRARY_PATH=<path>:<any other paths you want>
```
- Si estás ejecutando tu aplicación en Microsoft Windows, la ruta a las bibliotecas dinámicas (.dll) debe definirse en la variable de entorno PATH. 
- Si está ejecutando su aplicación en UNIX, la ruta a sus bibliotecas dinámicas (.so) debe definirse en la variable de entorno LD_LIBRARY_PATH. 

Esto debería resolver el problema por el momento, y le permitiría al compilador encontrar la librería sin ningún problema. De igual forma esto es temporal y voy a intentar resolver este problema para que no sea necesario ningún proceso de enlazado a parte del proceso de instalación de la librería, ya sea utilizando `ldconfig` o alguna otra herramienta que permita esto facilmente.

Cualquier otro aporte que puedas hacer a esta issue o a cml en general será bienvenido!

**Comment by lucasdc6** [comment]
Perfecto, gracias por la respuesta.
